module.exports = {
  english: "Your language has been changed to English",
  portugues: "Sua linguagem foi alterada para Portugues",
  NOT_CHANNEL_PT: "> Você precisa estar em um canal de voz!",
  NOT_CHANNEL_EU: "> You need to be on a voice channel!",
  NOT_PERM_CHANNEL_PT: "> Eu não tenho permissões para falar ou entrar no canal!",
  NOT_PERM_CHANNEL_EU: "> I don't have permission to speak or join the channel!",
  NOT_MUSIC_USE_PT: "> Você não me pediu nenhuma musica!",
  NOT_MUSIC_USE_EU: "> You didn't ask me for a song!",
  INIT_MUSIC_PT: "> 🎶 Iniciando musica",
  INIT_MUSIC_EU: "> 🎶 Starting music",
  NOT_CHANNEL_ENTER_PT: "> Não foi possivel entrar no canal",
  NOT_CHANNEL_ENTER_EU: "> Couldn't join channel",
  MUSIC_ADD_PT: "> Foi adicionada na playlist!",
  MUSIC_ADD_EU: "> It was added to the playlist!",
  NOT_HAVE_MUSIC_PT: "> Não a nada tocando no momento.",
  NOT_HAVE_MUSIC_EU: "> There's nothing playing at the moment.",
  CURRENT_VOLUME_PT: "> Volume atual",
  CURRENT_VOLUME_EU: "> Current volume",
  VOLUME_SET_PT: "> Novo volume setado",
  VOLUME_SET_EU: "> New set volume",
  CHANNEL_EXIT_PT: "> Saindo do canal",
  CHANNEL_EXIT_EU: "> Leaving the channel",
  MUSIC_SKIP_PT: "> Musica Trocada",
  MUSIC_SKIP_EU: "> Music Skip",
  MUSIC_RESUME_PT: "> Resume",
  MUSIC_RESUME_EU: "> Resume",
  MUSIC_PAUSE_PT: "> Pausado",
  MUSIC_PAUSE_EU: "> Paused",
  MUSIC_NOW_PT: "> Tocando Agora",
  MUSIC_NOW_EU: "> Playing Now",
  HELP_MESSAGE_HEAD_PT: "Comandos de Musica",
  HELP_MESSAGE_HEAD_EU: "Music Commands",
  HELP_MESSAGE_PT: "```Play - (Nome da musica) • Queue - (Para ver musicas em andamento)\nNP - (Musica tocando no momento) • Help - (Ajuda e comandos)\nPause - (Pausar musicas) • Resume - (Resumir musicas)\nSkip - (Trocar faixa) • Stop - (Pausar musicas)\nVolume - (Setar volume ou ver o atual) • Set - (!set language <portugues ou english>)\n\nBy Halo#1373```",
  HELP_MESSAGE_EU: "```Play - (Name of the song) • Queue - (To see music in progress)\nNP - (Music playing at the moment) • Help - (Help and commands)\nPause - (Pause music) • Resume - (Summarize songs)\nSkip - (Change Track) • Stop - (Stop music)\nVolume - (Set volume or view current) • Set - (!set language <portugues or english>)\n\nBy Halo#1373```",
  HELP_MESSAGE_DESCRIPTION_PT: "",
  HELP_MESSAGE_DESCRIPTION_EU: ""
}